<?php

$this	->inlineScript()
		->offsetSetScript(1, '$(function() { ds.init(); });');

$this	->headScript()
		->offsetSetFile(1, '/zkernel/js/jquery/jquery.js')
		->offsetSetFile(100, '/js/main.js')
		->offsetSetFile(200, $this->inlineSingle('filename'));

$this	->headLink()
		->offsetSetAlternate(150, array('rel' => 'favicon', 'href' => '/favicon.ico'))
		->offsetSetStylesheet(1, '/zkernel/img/reset.css', 'all')
		->offsetSetStylesheet(100, '/img/style.css', 'all');

$this	->headTitle($this->txt('site_title'), 'PREPEND')->setSeparator(' - ');

$this->meta();

echo $this->doctype('HTML5');

?>
<html>
	<head>
		<meta charset=utf-8>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->linkSingle() ?>
	</head>
	<body>
		<?php echo $this->layout()->content ?>
		<?php echo $this->headSingle() ?>
	</body>
</html>