<?php

$this	->headScript()
		->offsetSetFile(1, '/zkernel/js/jquery/jquery.js')
		->offsetSetFile(100, '/js/main.js');

$this	->inlineScript()
		->offsetSetScript(1, '$(function() { ds.init(); });');

$this	->headLink()
		->offsetSetAlternate(150, array('rel' => 'favicon', 'href' => '/favicon.ico'))
		->offsetSetStylesheet(100, '/img/style.css', 'all');

$this	->headMeta($this->txt('meta_keywords'), 'keywords')
		->headMeta($this->txt('meta_description'), 'description');

$this	->headTitle($this->txt('site_title'), 'PREPEND')->setSeparator(' - ');

echo $this->doctype('HTML5')

?>
<html>
	<head>
		<meta charset=utf-8>
		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink() ?>
	</head>
	<body>
		<?php echo $this->layout()->content ?>
		<?php echo $this->headSingle() ?>
		<?php echo $this->inlineSingle('file') ?>
	</body>
</html>